name: Unit Tests
on: [push , pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with: 
          go-version: '1.23.x'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
      - name: Test Suite
        run: go test -v ./...
